export default function AboutPage() {
  return (
    <div className="container-prose py-16">
      <p className="text-sm font-medium uppercase tracking-widest text-flag-green">About</p>
      <h1 className="mt-2 font-serif text-4xl font-semibold tracking-tight">
        Civic infrastructure for Nigerian democracy.
      </h1>

      <section className="mt-8 space-y-4 text-lg leading-relaxed text-foreground/85">
        <p>
          <strong className="text-foreground">Naija Bill Tracker</strong> is a free, non-partisan platform
          that follows bills moving through every Nigerian legislative body — the Senate, the House of
          Representatives, the 36 State Houses of Assembly plus the FCT, and Executive bills transmitted
          by the President.
        </p>
        <p>
          We exist because legislative transparency is fragmented in Nigeria. Bills are scattered across
          dozens of websites of varying quality, published mostly as PDFs, and written in dense legal
          language that excludes most citizens from participating in their own democracy. We close that
          gap.
        </p>
      </section>

      <h2 className="mt-16 font-serif text-2xl font-semibold tracking-tight">How bills get here</h2>
      <ol className="mt-4 space-y-4 text-foreground/85">
        <li><strong className="text-foreground">1. We watch the legislatures.</strong> Per-source jobs fetch bill index pages from official legislative websites and detect new or updated bills.</li>
        <li><strong className="text-foreground">2. We parse the text.</strong> Bill artifacts (HTML + PDFs) are extracted into machine-readable text. Scanned PDFs are OCR'd.</li>
        <li><strong className="text-foreground">3. We normalize and link.</strong> Each bill is mapped to a canonical record — number, title, sponsors, stage, source documents — and linked to existing legislators and topics.</li>
        <li><strong className="text-foreground">4. We translate it.</strong> A language model generates a plain-English explainer, classifies the bill against our topic taxonomy, and surfaces external coverage. Sensitive bills are flagged for human review.</li>
        <li><strong className="text-foreground">5. You can act on it.</strong> Follow bills you care about, contact your representatives, and discuss with other citizens.</li>
      </ol>

      <h2 className="mt-16 font-serif text-2xl font-semibold tracking-tight">Editorial principles</h2>
      <ul className="mt-4 list-disc space-y-2 pl-6 text-foreground/85">
        <li>Every plain-English explainer is generated by an LLM under a non-partisan system prompt and is grounded in the bill text and cited sources. Claims not supported by the source material are omitted.</li>
        <li>Bills touching security, elections, religion, ethnicity, or fiscal policy are flagged sensitive. Their explainers are held for editorial review before publication.</li>
        <li>Every explainer carries an "AI-generated, human-reviewed" badge and a way to report inaccuracies.</li>
        <li>We never edit the bill text itself. Source PDFs and Hansard links are preserved.</li>
      </ul>

      <h2 className="mt-16 font-serif text-2xl font-semibold tracking-tight">Contribute</h2>
      <p className="mt-4 text-foreground/85">
        If you find a bill we don't track, submit it. An editor will verify the source before
        publishing. State assembly contributions are especially welcome — they're the hardest for any
        single team to monitor without help.
      </p>

      <h2 className="mt-16 font-serif text-2xl font-semibold tracking-tight">Open source</h2>
      <p className="mt-4 text-foreground/85">
        Naija Bill Tracker is intended to ship open source under a permissive license. The ingestion
        methodology and the AI explainer prompts are designed to be auditable. Quarterly data dumps to
        GitHub and an open data portal are on the roadmap.
      </p>
    </div>
  );
}
